
export enum LocalStorageKeys {
    CURRENT_USER_INFO_LOCAL_STORAGE_KEY='CURRENT_USER_INFO_LOCAL_STORAGE_KEY',
    DEVICE_ID_KEY='DEVICE_ID_KEY',
	FAVORITES_PASSAGE_COMMAND_TYPE='FAVORITES_PASSAGE_COMMAND_TYPE'
}
